color: green
description: null
fieldLayouts:
  17a78ab3-2ba9-4302-86b8-a764a832705c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-19T13:54:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e22cc42-e872-4ba4-b3a0-e0780a5bd133
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-19T13:54:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bbf652b-cbdb-4d06-a839-2c6d7f5c8f09
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3145e23e-f765-4493-a8d8-bd29aaed07cd
        userCondition: null
handle: bodyWaitingList
hasTitleField: false
icon: null
name: 'Body: waiting list'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
