color: orange
description: null
fieldLayouts:
  8ed94e8c-5c9d-42c1-84fa-a572e0cf0c9c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-17T11:41:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 482ec28f-6a20-46fc-bdd3-a434c83e3905
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-17T11:41:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1b8422e-326b-4ec4-bc91-e31883ef2522
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-17T11:41:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 30dac077-6a88-402d-b9b1-e8ff0b4b6611
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de7d7262-5129-4bcf-8825-a0c2cecf677c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-17T12:31:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a4e8925-b372-4821-b28c-e88e30148bb3 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f43f4277-93d2-4e3d-b681-4a8f2ef7f0f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0dbdbc3-9bf8-4ebb-9db6-dece62632e4b
        userCondition: null
handle: bodyProducts
hasTitleField: false
icon: alicorn
name: 'Body: products'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
