color: green
description: null
fieldLayouts:
  6a37ae0a-65bd-4246-97a2-67624861642d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-20T08:31:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0089f003-a570-4313-8e57-4961f423ed25
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-20T08:31:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b2fd6268-2e91-41e0-aef5-c6f5cec40b27 # Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df15358b-73b1-44ff-b59e-b2a73865f37b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-20T08:31:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20e85ff3-1731-4e5d-8c96-851b18469c47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-20T08:31:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a4e8925-b372-4821-b28c-e88e30148bb3 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d83b6f27-b7c5-4718-b589-86b2cd365541
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d827a352-03c4-4bbe-80c5-6934472b5cfc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-24T19:26:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76632528-a976-4c20-b4a9-aa98f9d07874 # ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51901482-c419-4673-ac1c-5cbcc9bea3e3
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a3fcf770-1897-4c75-a825-83edb97a6808
        userCondition: null
handle: bodyNumbers
hasTitleField: false
icon: null
name: 'Body numbers'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
