color: green
description: null
fieldLayouts:
  cf2c2d0e-a254-4a36-8987-46b6a0125f0c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-20T08:25:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 301832f6-2868-4b99-8c6a-9878e0ecea80
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-20T08:25:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc98244a-d659-4e94-9589-e1c95cb67a37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-20T08:25:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b2fd6268-2e91-41e0-aef5-c6f5cec40b27 # Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 667353c3-d977-43bd-8a2d-c5caed16d3bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a5b035e7-83a6-43d2-a495-ac1c247d3a74
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-24T19:28:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76632528-a976-4c20-b4a9-aa98f9d07874 # ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 724a1112-807a-43cd-925f-4f1bf741a5cc
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 48a61065-bd15-47bf-85f1-05ab12bd7e43
        userCondition: null
handle: bodyTimeline
hasTitleField: false
icon: null
name: 'Body: timeline'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
