color: orange
description: null
fieldLayouts:
  232743dd-3f3d-492b-8520-c3a6dbb694bd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-16T13:12:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6e8d296e-8b80-4b94-96b3-6ae6e854ca88 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb6f0e38-fd80-4cb6-8b90-df5ea76e7009
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T13:12:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a4e8925-b372-4821-b28c-e88e30148bb3 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d385c1ab-8c27-4e92-bb7c-bc5a304db8f9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 965cd8cc-1bb2-49b8-b83e-4bdb85fc4702
        userCondition: null
handle: bodyVideo
hasTitleField: false
icon: video
name: 'Body: video'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
