color: green
description: null
fieldLayouts:
  c33b1d92-70e5-41a2-bae2-3bd464124188:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-18T19:04:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55d16975-e218-4a78-bf99-18e70e64e4c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-18T09:15:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0106a44-001a-4e9d-9372-a4c590bcaa2f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-18T09:15:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a4e8925-b372-4821-b28c-e88e30148bb3 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c6a1841-9d82-4cdf-b08c-0bce8d795089
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-18T19:04:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a27ac66-ce0f-493b-b744-3e9a411a9e54 # Teammembers
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5110d75d-bc9b-4a61-854e-7e36254e0f41
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a250cb7-daac-4e3b-a4fa-6faf98e7af9b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-24T19:25:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76632528-a976-4c20-b4a9-aa98f9d07874 # ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 682ee9e4-8b0b-453e-b192-39805abe3818
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 4cfcb97b-0a92-4a05-9af1-5ee1ca5435a7
        userCondition: null
handle: bodyAbout
hasTitleField: false
icon: null
name: 'Body: about'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
