color: null
description: null
fieldLayouts:
  9caf03dc-68eb-4f9f-b335-72a061358f14:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T16:05:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6e8d296e-8b80-4b94-96b3-6ae6e854ca88 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4801f34-7262-4170-89b5-6149920f251a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T16:05:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3245342c-9fba-4a4b-8a9f-b16efa775257
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31e0e1e8-a064-4709-9bf6-e29921e5bbb0
        userCondition: null
handle: commonImageBlock
hasTitleField: false
icon: null
name: 'Image block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
