color: null
description: null
fieldLayouts:
  8101f1a9-3373-41ff-bbe2-338e84602c23:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-13T11:41:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6e8d296e-8b80-4b94-96b3-6ae6e854ca88 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d428f58-7139-4e3e-83d8-698c542d0d21
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-13T11:41:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a4e8925-b372-4821-b28c-e88e30148bb3 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e2129fe-8486-443a-9ea5-d74271755ec9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01bad751-1c30-4468-b856-b78b24fe2fa9
        userCondition: null
handle: commonVideoBlock
hasTitleField: false
icon: null
name: 'Video block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
