color: null
description: null
fieldLayouts:
  fe1f98d1-8f24-4a36-8522-7c7bfd23285d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-18T18:58:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d87315db-ccbc-48ae-9958-d91d39bb28ad # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 107a09df-412e-4cd4-b355-f7df096f0272
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T18:44:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44127acd-20e7-44f0-ac16-f1d320ce27cc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T18:44:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09dbed55-0867-435b-8598-830742e19230
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T18:44:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6e8d296e-8b80-4b94-96b3-6ae6e854ca88 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 946cb8e7-4f1a-49b0-8848-21098c68e994
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-01T13:47:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5b665769-67a3-46f1-8870-7b07b789c28e # Coming soon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c141ea4-7fc3-40c9-92ef-f8288fbd77de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 052d40c1-4c6a-4316-8d2a-666650379daf
        userCondition: null
handle: feature
hasTitleField: false
icon: null
name: feature
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
