color: null
description: null
fieldLayouts:
  57877b44-7c0f-4215-8d0e-6e7dca759660:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-24T18:55:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffa900c0-5e00-4451-9ca7-47de4a0effc8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-24T18:59:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d87315db-ccbc-48ae-9958-d91d39bb28ad # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d0c0d2a-3182-4328-98f6-276322c36655
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-24T18:55:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b2fd6268-2e91-41e0-aef5-c6f5cec40b27 # Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fec7032b-dd55-4eb9-be9c-bdb660888eb1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e775b7a0-40a6-49a1-86b8-c6564bbb08bf
        userCondition: null
handle: schemaBlock
hasTitleField: false
icon: null
name: 'Schema block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{commonTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
