altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  7940565f-3793-42f9-bfe0-f7606f13aa37:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-09T12:38:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2d452adf-53f1-4299-b088-dd42fe462d14
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e795feda-dd7b-4c5c-8c91-5e2845b63355
        userCondition: null
fs: uploads
handle: uploads
name: uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
