columnSuffix: null
handle: commonIsComingSoon
instructions: null
name: 'Coming soon'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
