columnSuffix: null
handle: commonBody
instructions: null
name: Body
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 47957c38-67fa-4b6e-934b-41b7a37dc822 # Body: about
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 78c5f45e-0ac8-44b2-bada-2b3fef62a4af # Body: benefits
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - b8bf8ba8-f3f5-4b4e-ade3-ae8a16885069 # Body: contact
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 8c6f1534-ce1f-44c0-84d6-d6d49356de4f # Body: features
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - e5debc2e-300d-47e9-86db-5a469e3376ef # Body: schema
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - a96bdc50-6743-41da-a246-44735b3d6c1d # Body: stakeholder
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 74516331-f41c-439b-9c67-850bae4dff02 # Body: waiting list
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
