fieldLayouts:
  6d9af216-2f32-44c1-93a9-ca100bba11bb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-30T15:02:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb333504-3062-4751-b698-45c266d674a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2bb0b3de-9f47-493c-a217-206761bd1baa
        userCondition: null
handle: footer
name: footer
sortOrder: 1
