fieldLayouts:
  2ef3de9f-ed4c-4808-b4d2-d3863074769e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-18T19:25:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fa10e20e-af48-4184-9f2b-050e7fdda65e # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 446144bc-3d17-4369-aa74-209e5ad3578a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-30T15:14:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 79b4c55e-6c63-44b0-ab9f-a8e585d0e4f7
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae5073b3-20a7-443d-becc-426323dc05e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 35da4a77-0c82-4813-8d9d-6f7d46328230
        userCondition: null
handle: header
name: header
sortOrder: 3
