fieldLayouts:
  dbc2b214-1e46-475f-b87a-a952267fe938:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-30T15:02:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e0e8209-b831-4d86-a293-cc002bd867d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-30T15:02:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 79b4c55e-6c63-44b0-ab9f-a8e585d0e4f7
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 447d8adc-d248-4a07-8016-80b97528fbc0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 29c6a0b0-bb51-4f72-8979-db974d53b84f
        userCondition: null
handle: subfooter
name: subfooter
sortOrder: 2
