defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 365c9d07-5bc9-4680-bd19-2683c2980c5c # stakeholder
handle: stakeholder
maxAuthors: 1
name: stakeholder
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e1f2a3b4-5c6d-7e8f-9a0b-1c2d3e4f5a6b:
    enabledByDefault: true
    hasUrls: true
    template: stakeholder/_entry.twig
    uriFormat: 'stakeholder/{slug}'
structure:
  maxLevels: null
  uid: abf0f8d4-c331-4d52-bf3d-bb95b78a2e32
type: structure
